#ifndef GEMOS_USERLAND_ABOUT_THEME_H
#define GEMOS_USERLAND_ABOUT_THEME_H

#include "../common/app_theme.h"

#include <gemos/console_abi.h>

#define ABOUT_TITLE "About GemOS"
#define ABOUT_COLS 60U
#define ABOUT_ROWS 18U

#define ABOUT_HEADER_ROW 0U
#define ABOUT_HERO_ROW 2U
#define ABOUT_SUBTITLE_ROW 3U
#define ABOUT_SECTION_ROW 5U
#define ABOUT_FIELDS_ROW 7U
#define ABOUT_FOOTER_ROW 16U
#define ABOUT_CONTENT_COL GEMOS_APP_LAYOUT_MARGIN_X
#define ABOUT_LABEL_COL 4U
#define ABOUT_VALUE_COL 18U

#define ABOUT_STATUS_STYLE GEMOS_APP_STYLE_STATUS
#define ABOUT_TEXT_STYLE GEMOS_APP_STYLE_TEXT
#define ABOUT_DIM_STYLE GEMOS_APP_STYLE_DIM
#define ABOUT_ACCENT_STYLE GEMOS_APP_STYLE_ACCENT
#define ABOUT_ERROR_STYLE GEMOS_APP_STYLE_ERROR

#define ABOUT_VERSION_LABEL "0.1-dev"
#define ABOUT_BUILD_LABEL "Userland About MVP"

#endif /* GEMOS_USERLAND_ABOUT_THEME_H */
