#ifndef GEMOS_USERLAND_TEXTEDIT_THEME_H
#define GEMOS_USERLAND_TEXTEDIT_THEME_H

#include "../common/app_theme.h"

#include <gemos/console_abi.h>

#define UTEXTEDIT_TITLE "Text Editor"
#define UTEXTEDIT_COLS 84U
#define UTEXTEDIT_ROWS 28U

#define UTEXTEDIT_HEADER_ROW 0U
#define UTEXTEDIT_BODY_TOP_ROW 2U
#define UTEXTEDIT_STATUS_ROW (UTEXTEDIT_ROWS - 2U)
#define UTEXTEDIT_FOOTER_ROW (UTEXTEDIT_ROWS - 1U)
#define UTEXTEDIT_CONTENT_COL GEMOS_APP_LAYOUT_MARGIN_X
#define UTEXTEDIT_BODY_COLS (UTEXTEDIT_COLS - (UTEXTEDIT_CONTENT_COL * 2U))
#define UTEXTEDIT_BODY_ROWS (UTEXTEDIT_STATUS_ROW - UTEXTEDIT_BODY_TOP_ROW)

#define UTEXTEDIT_STATUS_STYLE GEMOS_APP_STYLE_STATUS
#define UTEXTEDIT_TEXT_STYLE GEMOS_APP_STYLE_TEXT
#define UTEXTEDIT_DIM_STYLE GEMOS_APP_STYLE_DIM
#define UTEXTEDIT_ACCENT_STYLE GEMOS_APP_STYLE_ACCENT
#define UTEXTEDIT_ERROR_STYLE GEMOS_APP_STYLE_ERROR

#endif /* GEMOS_USERLAND_TEXTEDIT_THEME_H */
