#ifndef GEMOS_USERLAND_COMMON_APP_THEME_H
#define GEMOS_USERLAND_COMMON_APP_THEME_H

#include <gemos/console_abi.h>

#define GEMOS_APP_LAYOUT_MARGIN_X 2U
#define GEMOS_APP_LAYOUT_MARGIN_Y 1U

#define GEMOS_APP_STYLE_STATUS GEMOS_CONSOLE_STYLE_STATUS
#define GEMOS_APP_STYLE_TEXT GEMOS_CONSOLE_STYLE_NORMAL
#define GEMOS_APP_STYLE_DIM GEMOS_CONSOLE_STYLE_DIM
#define GEMOS_APP_STYLE_ACCENT GEMOS_CONSOLE_STYLE_ACCENT
#define GEMOS_APP_STYLE_ERROR GEMOS_CONSOLE_STYLE_ERROR

#endif /* GEMOS_USERLAND_COMMON_APP_THEME_H */
