#ifndef UTERM2_TERM_THEME_H
#define UTERM2_TERM_THEME_H

#include "../common/app_theme.h"

#include <gemos/console_abi.h>

#define UTERM2_TITLE "GemOS Terminal"
#define UTERM2_PROMPT "gemos> "
#define UTERM2_HEADER_HINT "pid="
#define UTERM2_FOOTER_HINT "help  echo  clear  exit  pid  ticks"
#define UTERM2_FOOTER_CLOSE_HINT "Esc close"

#define UTERM2_COLS 80U
#define UTERM2_ROWS 25U
#define UTERM2_SCROLLBACK_LINES 32U
#define UTERM2_INPUT_MAX 96U
#define UTERM2_HISTORY_MAX 4U

#define UTERM2_HEADER_ROW 0U
#define UTERM2_TRANSCRIPT_ROW 2U
#define UTERM2_FOOTER_ROW (UTERM2_ROWS - 2U)
#define UTERM2_PROMPT_ROW (UTERM2_ROWS - 1U)
#define UTERM2_CONTENT_COL GEMOS_APP_LAYOUT_MARGIN_X

#define UTERM2_STATUS_STYLE GEMOS_APP_STYLE_STATUS
#define UTERM2_TEXT_STYLE GEMOS_APP_STYLE_TEXT
#define UTERM2_HINT_STYLE GEMOS_APP_STYLE_DIM
#define UTERM2_PROMPT_STYLE GEMOS_APP_STYLE_ACCENT
#define UTERM2_ERROR_STYLE GEMOS_APP_STYLE_ERROR

#endif /* UTERM2_TERM_THEME_H */
